### ISSUE TITLE
Step 2 of demo causes `Cannot read property '0' of undefined`

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/authorization.io#18]
When attempting to login to the issuer in step 2 of the demo, there are no mock credentials installed for the identity, causing the server to raise an `Cannot read property '0' of undefined` error in `tests/lib/idp.js` here: https://github.com/digitalbazaar/authorization.io/blob/0d2c18ae62097eba86bf44e5396ea14b5d62ddab/tests/lib/idp.js#L124

**Comment by msporny** [comment]
The mock credentials should be created when creating your identity. So, if you skip step #1, step #2 will fail. If the mock email credentials are no longer being created, that's an issue.

**Comment by dlongley** [comment]
Step 1 wasn't skipped when this bug occurred.

**Comment by dlongley** [comment]
Can't replicate after doing a full upgrade of npm and bower packages; closing.
