### ISSUE TITLE
Add a passphrase confirmation field on registration

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/authorization.io#20]
Since the passphrase is intended to be long (for security) and since it has greater significance than just a single account on a particular service (rather it is used to remember a DID used for federated login), we should require a confirmation field to ensure people don't make simple mistakes and get frustrated later when their passphrase doesn't work.

**Comment by erickorb** [comment]
Thanks!

Mr. Fat Fingers


*"Trust only credentials that are TrueCred*™ *verified."*
----------------------------------
Eric Korb, President/CEO - accreditrust.com <https://www.accreditrust.com>
GoogleVoice: 908-248-4252
http://www.linkedin.com/in/erickorb @erickorb @accreditrust

**Comment by mattcollier** [comment]
This issue was intended from bedrock-idp and was addressed with: https://github.com/digitalbazaar/bedrock-idp/commit/9bed4acad4463c3bbe6124b55cc8a9b5284cb117
