### ISSUE TITLE
Disable login button on identity chooser while loading

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/authorization.io#34]

**Comment by mattcollier** [comment]
This should already be the case: https://github.com/digitalbazaar/authorization.io/blob/master/components/identity-chooser/identity-chooser.html#L52-L54

Are you noticing unexpected behavior?

**Comment by dlongley** [comment]
Yeah, the `loading` vars weren't being used by login... and it needed some separate vars and other changes to work properly.

Fixed by a1f303fa6f93e901acbba14ab955d516287f5789.
