### ISSUE TITLE
Display identity name rather than email address in "select an identity" window.

### ISSUE THREAD

**Issue by creatinglake** [digitalbazaar/authorization.io#38]
When logging in or requesting credentials authorization.io is engaged and asks user to "select an identity". The identities displayed show email address rather than the identity name the user chose when creating that DID.  If the user has multiple identities associated with the same email address all they see is the same email address listed over and over again. I suggest displaying the Identity name rather than the email address.

**Comment by dlongley** [comment]
What `identity name` are you referring to? If it's one at a credential repository, that information is not available to authorization.io so it can't be shown. The only information available to authorization.io is that which is stored in the ledger, either directly in the DID object associated with the DID or via information that the user has entered to generate a lookup hash (e.g. email address falls into this category).

**Comment by creatinglake** [comment]
I am talking about the following view. It appears the field "email" does not require the input to be an email. I think I need to better understand auth.io. 

![select identity window](https://cloud.githubusercontent.com/assets/980136/18749370/91ce4282-80a4-11e6-9807-1a453508d031.jpg)

**Comment by dlongley** [comment]
Outdated, closing.
