### ISSUE TITLE
Add mocha and protractor tests

### ISSUE THREAD

**Issue by msporny** [digitalbazaar/authorization.io#4]
Add backend tests for:
- [x] successful DID document creation
- [x] failed DID document creation (perhaps several ways to fail)
- [ ] successful mapping creation (eg: a "login hash", but creating a 'mapping' should be designed to be agnostic of the mapping's use)
- [ ] failed mapping creation (perhaps several ways to fail)
- [x] performing a valid mapping query with a result
- [ ] performing a valid mapping query with no result
- [ ] performing an invalid mapping query (perhaps several ways to fail)
- what else?

Add frontend tests for:
- [x] IdP registration
- [x] Permanent key registration
- [ ] One-time use key registration
- [ ] Error cases for key registration
- [x] Credential transfer to relying party
- [ ] Rejected transfer to relying party (user elected to send nothing to the RP)
- what else?

**Comment by dlongley** [comment]
Out dated/design changed and simplified, closing.
