### ISSUE TITLE
Document REST API

### ISSUE THREAD

**Issue by harlantwood** [digitalbazaar/authorization.io#41]
Mentioned in #2 a while ago, but probably deserves an issue of its own.

In the meantime, AFAICT the application "routes" are in these files: https://github.com/digitalbazaar/authorization.io/search?q=routeProvider

Warning: I'm new to both this project and Angular. 😬

**Comment by harlantwood** [comment]
There are options that will "record" your usage of the API and create API docs (at least a starting point) for you.  

https://www.getpostman.com/ is a good recording solution, and https://github.com/sandeep89/doc-proxy , if you send requests in just the right way, will generate https://apiblueprint.org/ style docs...

**Comment by harlantwood** [comment]
@msporny @dlongley I am interested in using our own instance of this (auth.io) server for [this demo](https://github.com/CoMakery/trust-exchange/issues/17).

Even before having real API docs, it would be helpful to understand the moving parts from an API perspective, eg for each step listed in https://github.com/digitalbazaar/authorization.io#core-functionality -- what are the api endpoint(s) hit for each step?

**Comment by dlongley** [comment]
There's no longer a REST API to document, this has been simplified to client-side only code, closing.
