### ISSUE TITLE
"No available storage method found." in firefox

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/authorization.io#76]
![storage-auth-1](https://user-images.githubusercontent.com/278280/72848636-0752e480-3c73-11ea-86fa-d763147055e4.png)

```
   setDriverToConfig();
                    var error = new Error('No available storage method found.');
                    self._driverSet = Promise$1.reject(error);
                    return self._driverSet;
                }

                return driverPromiseLoop();
            };
        }
```
//# sourceURL=https://authorization.localhost:33443/modules/localforage/dist/localforage.js

this appears to have something to do with localforage.

**Comment by dlongley** [comment]
CHAPI is not available in private browsing mode in a number of browsers. There is no fix for that and no intention to create one; don't use CHAPI in private browsing mode.
